version: "3.9"

services:
  falcare:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: falcare
    environment:
      NODE_ENV: production
      PORT: 3000
    ports:
      - "2313:3000" # host:container
    restart: unless-stopped
